import type { Claim, Token } from "@/lib/data";

/**
 * Sample rows for screenshots and for walking the interface before there is
 * anything on chain
 *
 * Nothing here loads unless demoData is turned on in site-config.json
 */

export const DEMO_TOKENS: Token[] = [
  {
    id: "ledger-cat",
    mint: "7GkQmARuK3xy9pLd2V8sNfTcH1bZoW4eXjMv6RsUq5Yn",
    name: "Ledger Cat",
    symbol: "LCAT",
    status: "live",
    owner: "+141 ••• 7712",
    launchedAgo: "6m ago",
    ageMinutes: 6,
    marketCap: 199_400,
    holders: 1_284,
    feesAccrued: 3_210,
    feesClaimed: 2_568,
  },
  {
    id: "paper-bag",
    mint: "2QpLxRt8vNcKdF3mZaHbY7wJuE1sPgQ6TiVn4XoBr9Cd",
    name: "Paper Bag",
    symbol: "BAG",
    status: "live",
    owner: "+4477 ••• 0007",
    assignedTo: "+346 ••• 5619",
    launchedAgo: "31m ago",
    ageMinutes: 31,
    marketCap: 174_050,
    holders: 903,
    feesAccrued: 2_025,
    feesClaimed: 0,
  },
  {
    id: "stonk-cat",
    mint: "9XcVbN2mQwErTy6uIoP4aSdFgHjKlZx8CvBnM1qWe3Rt",
    name: "Stonk Cat",
    symbol: "STONK",
    status: "live",
    owner: "+9198 ••• 3365",
    launchedAgo: "11m ago",
    ageMinutes: 11,
    marketCap: 100_120,
    holders: 612,
    feesAccrued: 1_470,
    feesClaimed: 0,
  },
  {
    id: "money-futurist",
    mint: "4RdTgBnMkLpOiUyTrEwQaZxSvCfDgHjNbVcXm2Qw7Er9",
    name: "Money Futurist",
    symbol: "FUTUR",
    status: "graduated",
    owner: "+6281 ••• 4058",
    launchedAgo: "18m ago",
    ageMinutes: 18,
    marketCap: 412_800,
    holders: 2_940,
    feesAccrued: 5_055,
    feesClaimed: 4_044,
  },
  {
    id: "the-underdog",
    mint: "8KtYuIoPlKjHgFdSaZxCvBnM4qWeRtYu7IoPl2KjHgFd",
    name: "The Underdog",
    symbol: "DOG",
    status: "live",
    owner: "+3806 ••• 2674",
    launchedAgo: "12m ago",
    ageMinutes: 12,
    marketCap: 3_640,
    holders: 78,
    feesAccrued: 180,
    feesClaimed: 144,
  },
  {
    id: "night-shift",
    mint: "3LyKjHgFdSaZxCvBnMqWeRtYuIoPlKjHgFdSaZxCvBn8",
    name: "Night Shift",
    symbol: "NIGHT",
    status: "live",
    owner: "+346 ••• 5619",
    launchedAgo: "48m ago",
    ageMinutes: 48,
    marketCap: 98_400,
    holders: 501,
    feesAccrued: 1_065,
    feesClaimed: 852,
  },
];

export const DEMO_CLAIMS: Claim[] = [
  {
    id: "c-1",
    tokenId: "money-futurist",
    amount: 4044,
    wallet: "9mTz…4kLp",
    ago: "2m",
    tx: "CfB7q78Hz2r51J8hXU3pF",
  },
  {
    id: "c-2",
    tokenId: "ledger-cat",
    amount: 2568,
    wallet: "4kPq…9xAt",
    ago: "31m",
    tx: "CfB7q77o4KAmsjfYoLZQi",
  },
  {
    id: "c-3",
    tokenId: "night-shift",
    amount: 852,
    wallet: "1aSd…5fGh",
    ago: "2h",
    tx: "CfB7q6vtj4wkNfswvPW91",
  },
  {
    id: "c-4",
    tokenId: "the-underdog",
    amount: 144,
    wallet: "8zXc…6vBn",
    ago: "5h",
    tx: "CfB7q6xNyGSH54FFzXGDZ",
  },
];
